# Generated by Django 5.2.6 on 2025-10-01 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_service_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='products',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='services',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='contact',
        ),
        migrations.AddField(
            model_name='shop',
            name='contact_number',
            field=models.CharField(default='0000000000', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='shop',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='shop',
            name='products',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.AddField(
            model_name='shop',
            name='services',
            field=models.JSONField(default=list),
        ),
    ]
